import type { RSVPEntry, WishEntry } from "@/types/admin"

export const mockRSVP: RSVPEntry[] = [
  {
    id: "1",
    nama: "Budi Santoso",
    jumlah_tamu: 2,
    kehadiran: "hadir",
    pesan: "Selamat ya, semoga sakinah mawaddah warahmah!",
    created_at: "2026-05-10T08:23:00Z",
  },
  {
    id: "2",
    nama: "Dewi Lestari",
    jumlah_tamu: 1,
    kehadiran: "hadir",
    pesan: "Tidak sabar menghadiri hari bahagia kalian.",
    created_at: "2026-05-10T09:15:00Z",
  },
  {
    id: "3",
    nama: "Rangga Pratama",
    jumlah_tamu: 4,
    kehadiran: "hadir",
    pesan: "Bawa keluarga ya, sampai jumpa di Jakarta!",
    created_at: "2026-05-11T14:02:00Z",
  },
  {
    id: "4",
    nama: "Maya Anggraini",
    jumlah_tamu: 1,
    kehadiran: "tidak_hadir",
    pesan: "Maaf belum bisa hadir, doa terbaik dari jauh.",
    created_at: "2026-05-11T16:40:00Z",
  },
  {
    id: "5",
    nama: "Hendra Wijaya",
    jumlah_tamu: 2,
    kehadiran: "belum_pasti",
    pesan: "InsyaAllah hadir, masih konfirmasi jadwal.",
    created_at: "2026-05-12T07:18:00Z",
  },
  {
    id: "6",
    nama: "Sari Indah",
    jumlah_tamu: 3,
    kehadiran: "hadir",
    pesan: "Tentu saja datang! Sampai ketemu di pelaminan.",
    created_at: "2026-05-12T10:55:00Z",
  },
  {
    id: "7",
    nama: "Ahmad Rifai",
    jumlah_tamu: 2,
    kehadiran: "hadir",
    created_at: "2026-05-12T11:30:00Z",
  },
  {
    id: "8",
    nama: "Lina Putri",
    jumlah_tamu: 1,
    kehadiran: "tidak_hadir",
    pesan: "Maaf sedang di luar kota, semoga lancar acaranya.",
    created_at: "2026-05-13T08:00:00Z",
  },
  {
    id: "9",
    nama: "Faisal Akbar",
    jumlah_tamu: 5,
    kehadiran: "hadir",
    pesan: "Bismillah, sekeluarga akan hadir!",
    created_at: "2026-05-13T13:22:00Z",
  },
  {
    id: "10",
    nama: "Rina Kartika",
    jumlah_tamu: 2,
    kehadiran: "belum_pasti",
    created_at: "2026-05-13T18:45:00Z",
  },
  {
    id: "11",
    nama: "Doni Saputra",
    jumlah_tamu: 1,
    kehadiran: "hadir",
    pesan: "Pasti datang, semoga jadi keluarga sakinah.",
    created_at: "2026-05-14T07:50:00Z",
  },
  {
    id: "12",
    nama: "Wulan Sari",
    jumlah_tamu: 2,
    kehadiran: "hadir",
    pesan: "Selamat menempuh hidup baru!",
    created_at: "2026-05-14T09:33:00Z",
  },
]

export const mockWishes: WishEntry[] = [
  {
    id: "w1",
    nama: "Budi Santoso",
    pesan: "Barakallahu laka wa baraka 'alaika wa jama'a bainakuma fii khair. Selamat ya Ahmad & Siti!",
    created_at: "2026-05-10T08:25:00Z",
    status: "approved",
  },
  {
    id: "w2",
    nama: "Dewi Lestari",
    pesan: "Semoga menjadi keluarga sakinah, mawaddah, warahmah. Bahagia selalu untuk kalian berdua.",
    created_at: "2026-05-10T09:18:00Z",
    status: "approved",
  },
  {
    id: "w3",
    nama: "Rangga Pratama",
    pesan: "Akhirnya nikah juga! Selamat brother, doa terbaik untuk kalian.",
    created_at: "2026-05-11T14:05:00Z",
    status: "approved",
  },
  {
    id: "w4",
    nama: "Maya Anggraini",
    pesan: "Selamat menempuh hidup baru. Semoga langgeng sampai surga.",
    created_at: "2026-05-11T16:43:00Z",
    status: "approved",
  },
  {
    id: "w5",
    nama: "Hendra Wijaya",
    pesan: "Selamat ya! Sukses dunia akhirat.",
    created_at: "2026-05-12T07:21:00Z",
    status: "pending",
  },
  {
    id: "w6",
    nama: "Sari Indah",
    pesan: "Cinta yang baik adalah cinta yang membawa pada kebaikan. Selamat untuk kalian berdua.",
    created_at: "2026-05-12T10:58:00Z",
    status: "approved",
  },
  {
    id: "w7",
    nama: "Anonim",
    pesan: "Pesan dengan link mencurigakan http://spam-example.com selamat ya",
    created_at: "2026-05-12T15:00:00Z",
    status: "pending",
  },
  {
    id: "w8",
    nama: "Lina Putri",
    pesan: "Semoga menjadi pasangan yang saling melengkapi dalam suka dan duka.",
    created_at: "2026-05-13T08:03:00Z",
    status: "approved",
  },
]
